"""migrate

Revision ID: eeaefc20907c
Revises: 923715e884d8
Create Date: 2022-04-06 14:53:06.332379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeaefc20907c'
down_revision = '923715e884d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'slug',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'slug',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
    # ### end Alembic commands ###
